### ISSUE TITLE
示例服务器已无法使用

### ISSUE THREAD

**Issue by KingSingularity** [genshen/wssocks-plugin-ustb#13]

**Comment by genshen** [comment]
你可以参考下文档截图里面的配置示例： https://genshen.github.io/wssocks-plugin-ustb/#/zh-cn/wssocks-client ，其中一个公用的 wssocks 服务器地址 (remote address) 是 `wss://proxy.gensh.me` (协议项是 wss，不是 ws)。

如果还有问题，欢迎继续反馈。

**Comment by genshen** [comment]
No more feedback, close it. Please reopen it if there is any progress.
