### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by caolz** [genshen/wssocks-plugin-ustb#26]
![A$HD1OR6~NRJ8NKSDK%_P5F](https://github.com/genshen/wssocks-plugin-ustb/assets/49866647/0db8357e-9022-488f-bbb6-e67c49c7aeeb)
Now logging in after entering the password encounters this error.

**Comment by genshen** [comment]
Duplicated issue, see #24.

Quick answer: change vpn host to lib.ustb.edu.cn (password login), or use our develop version in GitHub action building (WeChat QR code login + password login).
